apiVersion: v1
kind: ConfigMap
metadata:
  name: observability-metrics-custom-allowlist
  namespace: openshift-monitoring 
data:
  metrics_list.yaml: |
    names:
      - kube_persistentvolumeclaim_info
      - container_cpu_usage_seconds_total
      - node_disk_writes_completed_total
      - kube_storageclass_info
      - node_network_receive_bytes_total
      - node_network_info
      - node_network_transmit_bytes_total
      - node_network_speed_bytes
      - node_network_mtu_bytes
      - node_network_up
      - node_disk_read_bytes_total
      - node_disk_reads_completed_total
      - node_disk_writes_completed_total
      - node_disk_written_bytes_total
      - node_disk_read_time_seconds_total
      - node_disk_write_time_seconds_total
      - kubelet_volume_stats_used_bytes
      - kubelet_volume_stats_capacity_bytes
