{
 "title": "ODF Multi-Cluster Performance Analysis",
 "tags": [
  "odf",
  "multi-cluster",
  "ceph"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(ceph_health_status, cluster)"
    }
   },
   {
    "name": "worker",
    "label": "Worker",
    "query": {
     "query": "label_values(kube_node_role{cluster=~\"$cluster\", role=~'(worker|infra)'}, node)"
    }
   },
   {
    "name": "rbd_device",
    "label": "rbd Device",
    "query": {
     "query": "label_values(node_disk_read_bytes_total{cluster=~\"$cluster\", instance=~\"$worker.*\", device=~\"rbd.*\"}, device)"
    }
   },
   {
    "name": "pvc",
    "label": "ODF PVC Name",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info{cluster=~\"$cluster\", storageclass=~\"ocs-storagecluster.*\"},persistentvolumeclaim)"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "ocs_version",
    "query": {
     "query": "label_values(ocs_exporter_version{cluster=~\"$cluster\"}, version)"
    }
   },
   {
    "name": "ceph_version",
    "query": {
     "query": "label_values(ceph_mon_metadata{cluster=~\"$cluster\"}, ceph_version)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ceph Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Ceph Health",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ceph_health_status{cluster=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "OCS Version",
     "type": "text",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
     "options": {
      "content": "<br>\n<center><h1>${ocs_version}</h1></center>"
     }
    },
    {
     "title": "Ceph Version",
     "type": "text",
     "description": "ceph version based on the version running in the monitors",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
     "options": {
      "content": "<br>\n<center><h1>${ceph_version}</h1></center>"
     }
    },
    {
     "title": "OSD Nodes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count by(cluster, instance) (ceph_disk_occupation{cluster=~\"$cluster\"}))"
      }
     ]
    },
    {
     "title": "OSDs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(ceph_osd_metadata{cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "OSD Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(ceph_osd_stat_bytes{cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Raw Capacity",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ceph_osd_stat_bytes{cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Pools",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(ceph_pool_metadata{cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Storageclasses",
     "type": "stat",
     "description": "ODF (noobaa and ceph) storage classes",
     "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_storageclass_info{cluster=~\"$cluster\", provisioner=~\"openshift-storage.*\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "RBD PV Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_persistentvolumeclaim_info{cluster=~\"$cluster\", storageclass=\"ocs-storagecluster-ceph-rbd\"})"
      }
     ]
    },
    {
     "title": "cephfs PV Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_persistentvolumeclaim_info{cluster=~\"$cluster\", storageclass=\"ocs-storagecluster-cephfs\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Total Ceph CPU Core Usage",
     "type": "timeseries",
     "description": "Includes mgr,mons,osds and rbd-mirror daemons",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(label_replace(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=~\"$cluster\", container=~\"osd|rbd-mirror|mgr|mon|mds|rgw\", namespace=\"openshift-storage\"},\"daemon\", \"$1\", \"pod\", \"rook-ceph-(.*)\"))",
       "legendFormat": "{{cluster}} - Total CPU"
      }
     ]
    },
    {
     "title": "Cluster IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "round(((rate(ceph_pool_rd{cluster=~\"$cluster\"}[10m]) + rate(ceph_pool_wr{cluster=~\"$cluster\"}[10m])) * on(cluster, pool_id) group_left(name) (ceph_pool_metadata{cluster=~\"$cluster\"})),1)",
       "legendFormat": "{{cluster}} - {{name}}"
      }
     ]
    },
    {
     "title": "Cluster Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(rate(ceph_pool_rd_bytes{cluster=~\"$cluster\"}[10m]) + rate(ceph_pool_wr_bytes{cluster=~\"$cluster\"}[10m])) * on(cluster, pool_id) group_left(name) (ceph_pool_metadata{cluster=~\"$cluster\"})",
       "legendFormat": "{{cluster}} - {{name}}"
      }
     ]
    },
    {
     "title": "Cluster Capacity Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ceph_cluster_total_bytes{cluster=~\"$cluster\"}",
       "legendFormat": "{{cluster}} - Total Raw"
      },
      {
       "expr": "ceph_cluster_total_used_raw_bytes{cluster=~\"$cluster\"}",
       "legendFormat": "{{cluster}} - Used Raw"
      },
      {
       "expr": "ceph_cluster_total_bytes{cluster=~\"$cluster\"} *.85",
       "legendFormat": "{{cluster}} - CLUSTER_FULL Threshold (85%)"
      }
     ]
    },
    {
     "title": "Client IOPS (rbd* devices)",
     "type": "timeseries",
     "description": "Total of IOPS for rbd devices within the cluster",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "round(sum by(cluster) (rate(ceph_rbd_read_ops{cluster=~\"$cluster\"}[10m])),1)",
       "legendFormat": "{{cluster}} - Reads"
      },
      {
       "expr": "round(sum by(cluster) (rate(ceph_rbd_write_ops{cluster=~\"$cluster\"}[10m])),1)",
       "legendFormat": "{{cluster}} - Writes"
      }
     ]
    }
   ]
  },
  {
   "title": "Noobaa Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Noobaa Health",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(NooBaa_health_status{cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Buckets",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(NooBaa_bucket_status{cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Buckets in Error",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(noobaa_bucket_status{cluster=~\"$cluster\"} == 0) or vector(0)"
      }
     ]
    },
    {
     "title": "OBCs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "NooBaa_num_buckets_claims{cluster=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Object Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "NooBaa_num_objects_buckets_claims{cluster=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Quotas Set",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(NooBaa_bucket_size_quota{cluster=~\"$cluster\"} > 0) or vector(0)"
      }
     ]
    },
    {
     "title": "Savings",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(NooBaa_object_savings_logical_size{cluster=~\"$cluster\"} - NooBaa_object_savings_physical_size{cluster=~\"$cluster\"}) "
      }
     ]
    },
    {
     "title": "Data Reduction",
     "type": "stat",
     "description": "Data reduction ratio",
     "gridPos": { "h": 4, "w": 2, "x": 14, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "NooBaa_reduction_ratio{cluster=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Capacity Used",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 2, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "NooBaa_system_capacity{cluster=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Usage by bucketclass",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max by(cluster, bucket_class) (NooBaa_bucket_class_capacity_usage{cluster=~\"$cluster\"})",
       "legendFormat": "{{bucket_class}}"
      }
     ]
    },
    {
     "title": "Total Noobaa CPU Core Usage",
     "type": "timeseries",
     "description": "Sum of cpu usage for ALL noobaa daemons expessed as a percentage of cpu cores (i.e. > 100% = 1 core, 200% = 2 cores)",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=~\"$cluster\", container=~\"noobaa|core|db|endpoint\", namespace=\"openshift-storage\"})",
       "legendFormat": "{{cluster}} - Total CPU"
      }
     ]
    },
    {
     "title": "Noobaa Provider R/W OPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "round(sum by(cluster, namespace, managedBy, job, service) (rate(NooBaa_providers_ops_read_num{cluster=~\"$cluster\"}[10m])),1)",
       "legendFormat": "{{cluster}} - Read OPs "
      },
      {
       "expr": "round(sum by(cluster, namespace, managedBy, job, service) (rate(NooBaa_providers_ops_write_num{cluster=~\"$cluster\"}[10m])),1)",
       "legendFormat": "{{cluster}} - Write OPs"
      }
     ]
    },
    {
     "title": "Noobaa Provider R/W Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(cluster, namespace, managedBy, job, service) (rate(NooBaa_providers_bandwidth_read_size{cluster=~\"$cluster\"}[10m]))",
       "legendFormat": "{{cluster}} - Read Throughput"
      },
      {
       "expr": "sum by(cluster, namespace, managedBy, job, service) (rate(NooBaa_providers_bandwidth_write_size{cluster=~\"$cluster\"}[10m]))",
       "legendFormat": "{{cluster}} - Write Throughput"
      }
     ]
    },
    {
     "title": "Capacity Used vs Object count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(noobaa_total_usage{cluster=~\"$cluster\"})",
       "legendFormat": "{{cluster}} - Total Used"
      },
      {
       "expr": "max(job:noobaa_total_object_count:sum{cluster=~\"$cluster\"})",
       "legendFormat": "{{cluster}} - Object Count"
      }
     ]
    },
    {
     "title": "Object Size Distribution",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "NooBaa_object_histo{cluster=~\"$cluster\"} > 0",
       "legendFormat": "{{size}}"
      }
     ]
    },
    {
     "title": "Noobaa Endpoints Active",
     "type": "timeseries",
     "description": "Count of the number of noobaa endpoints in the cluster. The red line depicts the scaling limit.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(kube_pod_info{cluster=~\"$cluster\", pod=~\"noobaa-endpoint.*\", namespace=\"openshift-storage\"})",
       "legendFormat": "{{cluster}} - Endpoints Active"
      }
     ]
    }
   ]
  },
  {
   "title": "radosGW Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "RGW Daemons",
     "type": "stat",
     "description": "Count of 'active' radosgw daemons",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(ceph_rgw_metadata{cluster=~\"$cluster\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Radosgw CPU Core Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 2, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=~\"$cluster\", container=~\"rgw\", namespace=\"openshift-storage\"},\"daemon\", \"$1\", \"pod\", \"rook-ceph-(.*)\")",
       "legendFormat": "{{cluster}} - {{pod}}"
      }
     ]
    },
    {
     "title": "GET/PUT Throughput - All Instances",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "round(sum(rate(ceph_rgw_get_b{cluster=~\"$cluster\"}[10m])),1)",
       "legendFormat": "{{cluster}} - GET bytes"
      },
      {
       "expr": "round(sum(rate(ceph_rgw_put_b{cluster=~\"$cluster\"}[10m])),1)",
       "legendFormat": "{{cluster}} - PUT bytes"
      }
     ]
    },
    {
     "title": "Requests/sec",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum(rate(ceph_rgw_req{cluster=~\"$cluster\"}[10m])),1)"
      }
     ]
    },
    {
     "title": "Q Length",
     "type": "stat",
     "description": "Requests queue length",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(avg(ceph_rgw_qlen{cluster=~\"$cluster\"}),1)"
      }
     ]
    },
    {
     "title": "GET/PUTs - All Instances",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 2, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "round(sum(rate(ceph_rgw_get{cluster=~\"$cluster\"}[10m])),1)",
       "legendFormat": "{{cluster}} - GET ops"
      },
      {
       "expr": "round(sum(rate(ceph_rgw_put{cluster=~\"$cluster\"}[10m])),1)",
       "legendFormat": "{{cluster}} - PUT ops"
      }
     ]
    },
    {
     "title": "GET/PUT Latencies - All Instances",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(ceph_rgw_get_initial_lat_sum{cluster=~\"$cluster\"}[10m]) / rate(ceph_rgw_get_initial_lat_count{cluster=~\"$cluster\"}[10m]))",
       "legendFormat": "{{cluster}} - GET latency"
      },
      {
       "expr": "sum(rate(ceph_rgw_put_initial_lat_sum{cluster=~\"$cluster\"}[10m]) / rate(ceph_rgw_put_initial_lat_count{cluster=~\"$cluster\"}[10m]))",
       "legendFormat": "{{cluster}} - PUT latency"
      }
     ]
    },
    {
     "title": "Q Active",
     "type": "stat",
     "description": "Active Requests Queue",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(avg(ceph_rgw_qactive{cluster=~\"$cluster\"}),1)"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total PGs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ceph_pg_total{cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "PG Count by Pool",
     "type": "timeseries",
     "description": "This is the primary PG count",
     "gridPos": { "h": 8, "w": 7, "x": 2, "y": 4 },
     "targets": [
      {
       "expr": "ceph_pg_total{cluster=~\"$cluster\"} * on(cluster, pool_id) group_left(name) (ceph_pool_metadata{cluster=~\"$cluster\"})",
       "legendFormat": "{{cluster}} - {{ name }}"
      }
     ]
    },
    {
     "title": "PG Distribution ",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "ceph_osd_numpg{cluster=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "OSD Usage over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(ceph_osd_stat_bytes_used{cluster=~\"$cluster\"} / ceph_osd_stat_bytes{cluster=~\"$cluster\"}) * 100",
       "legendFormat": "{{cluster}} - {{ceph_daemon}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Physical Disk Activity - by Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total IOPS by Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(cluster, hostname) (rate(ceph_osd_op{cluster=~\"$cluster\"}[10m]) * on(cluster, ceph_daemon) group_left(hostname) ceph_osd_metadata{cluster=~\"$cluster\"})",
       "legendFormat": "{{cluster}} - {{hostname}}"
      }
     ]
    },
    {
     "title": "Total Disk Bandwidth by Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(cluster, hostname) ((rate(ceph_osd_op_in_bytes{cluster=~\"$cluster\"}[10m]) + rate(ceph_osd_op_out_bytes{cluster=~\"$cluster\"}[10m])) * on(cluster, ceph_daemon) group_left(hostname) ceph_osd_metadata{cluster=~\"$cluster\"})",
       "legendFormat": "{{cluster}} - {{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Physical Disk Activity - by OSD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "WRITE IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "rate(ceph_osd_op{cluster=~\"$cluster\"}[10m]) - rate(ceph_osd_op_r{cluster=~\"$cluster\"}[10m])",
       "legendFormat": "{{cluster}} - {{ceph_daemon}}"
      },
      {
       "expr": "sum by(cluster) (rate(ceph_osd_op{cluster=~\"$cluster\"}[10m]) - rate(ceph_osd_op_r{cluster=~\"$cluster\"}[10m]))",
       "legendFormat": "{{cluster}} - Total Write IOPS"
      }
     ]
    },
    {
     "title": "WRITE Latencies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(ceph_osd_op_latency_sum{cluster=~\"$cluster\"}[10m]) - rate(ceph_osd_op_r_latency_sum{cluster=~\"$cluster\"}[10m])) / clamp_min(rate(ceph_osd_op_latency_count{cluster=~\"$cluster\"}[10m]) - rate(ceph_osd_op_r_latency_count{cluster=~\"$cluster\"}[10m]), 1)",
       "legendFormat": "{{cluster}} - {{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "WRITE Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(ceph_osd_op_in_bytes{cluster=~\"$cluster\"}[10m])",
       "legendFormat": "{{cluster}} - {{ceph_daemon}}"
      },
      {
       "expr": "sum by(cluster) (rate(ceph_osd_op_in_bytes{cluster=~\"$cluster\"}[10m]))",
       "legendFormat": "{{cluster}} - Total Write Throughput"
      }
     ]
    },
    {
     "title": "Average Write IO Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(ceph_osd_op_in_bytes{cluster=~\"$cluster\"}[10m]) / clamp_min(rate(ceph_osd_op{cluster=~\"$cluster\"}[10m]) - rate(ceph_osd_op_r{cluster=~\"$cluster\"}[10m]), 1)",
       "legendFormat": "{{cluster}} - {{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "Read IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "rate(ceph_osd_op_r{cluster=~\"$cluster\"}[10m])",
       "legendFormat": "{{cluster}} - {{ceph_daemon}}"
      },
      {
       "expr": "sum by(cluster) (rate(ceph_osd_op_r{cluster=~\"$cluster\"}[10m]))",
       "legendFormat": "{{cluster}} - Total Read IOPS"
      }
     ]
    },
    {
     "title": "READ Latencies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(ceph_osd_op_r_latency_sum{cluster=~\"$cluster\"}[10m]) / clamp_min(rate(ceph_osd_op_r_latency_count{cluster=~\"$cluster\"}[10m]), 1)",
       "legendFormat": "{{cluster}} - {{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "READ Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(ceph_osd_op_r_out_bytes{cluster=~\"$cluster\"}[10m])",
       "legendFormat": "{{cluster}} - {{ceph_daemon}}"
      },
      {
       "expr": "sum by(cluster) (rate(ceph_osd_op_r_out_bytes{cluster=~\"$cluster\"}[10m]))",
       "legendFormat": "{{cluster}} - Total READ Throughput"
      }
     ]
    },
    {
     "title": "Average Read IO Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(ceph_osd_op_r_out_bytes{cluster=~\"$cluster\"}[10m]) / clamp_min(rate(ceph_osd_op_r{cluster=~\"$cluster\"}[10m]), 1)",
       "legendFormat": "{{cluster}} - {{ceph_daemon}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Networking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Bandwidth by Host",
     "type": "timeseries",
     "description": "Network receive + transmit bytes for all active (UP) physical interfaces on each host in the cluster",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(sum by(cluster, instance) (rate(node_network_receive_bytes_total{cluster=~\"$cluster\", device=~\"(eth|en).*\"}[10m]) * on(cluster, instance, device) node_network_info{cluster=~\"$cluster\", operstate=\"up\"})) +\n(sum by(cluster, instance) (rate(node_network_transmit_bytes_total{cluster=~\"$cluster\", device=~\"(eth|en).*\"}[10m]) * on(cluster, instance, device) node_network_info{cluster=~\"$cluster\", operstate=\"up\"}))",
       "legendFormat": "{{cluster}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Network Load : $worker",
     "type": "timeseries",
     "description": "Network receive + transmit bytes for all active (UP) physical interfaces on each host in the cluster",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(rate(node_network_receive_bytes_total{cluster=~\"$cluster\", instance=\"$worker\",device=~\"(eth|en).*\"}[10m]) * on(cluster, instance, device) node_network_info{cluster=~\"$cluster\", operstate=\"up\"})",
       "legendFormat": "{{cluster}} - {{device}}/RX"
      },
      {
       "expr": "(rate(node_network_transmit_bytes_total{cluster=~\"$cluster\", instance=\"$worker\",device=~\"(eth|en).*\"}[10m]) * on(cluster, instance, device) node_network_info{cluster=~\"$cluster\", operstate=\"up\"}) * -1",
       "legendFormat": "{{cluster}} - {{device}}/TX"
      }
     ]
    },
    {
     "title": "NIC Configuration : $worker",
     "type": "table",
     "description": "Links speed and MTU size on physical interfaces in an UP state",
     "gridPos": { "h": 9, "w": 7, "x": 16, "y": 43 },
     "targets": [
      {
       "expr": "node_network_up{cluster=~\"$cluster\", instance=\"$worker\",device=~\"(eth|en).*\"} * on(cluster, instance, device) node_network_info{cluster=~\"$cluster\", operstate=\"up\"}"
      },
      {
       "expr": "node_network_mtu_bytes{cluster=~\"$cluster\", instance=\"$worker\",device=~\"(eth|en).*\"} * on(cluster, instance, device) node_network_info{cluster=~\"$cluster\", operstate=\"up\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ceph CPU / Memory Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Ceph Daemon CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=~\"$cluster\", container=~\"osd|rbd-mirror|mgr|mon|mds|rgw\", namespace=\"openshift-storage\"},\"daemon\", \"$1\", \"pod\", \"rook-ceph-(.*)\")",
       "legendFormat": "{{cluster}} - {{daemon}}"
      }
     ]
    },
    {
     "title": "Ceph Daemon Memory Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "label_replace(container_memory_working_set_bytes{cluster=~\"$cluster\", container=~\"osd|rbd-mirror|mgr|mon|mds|rgw\", namespace=\"openshift-storage\"},\"daemon\", \"$1\", \"pod\", \"rook-ceph-(.*)\")",
       "legendFormat": "{{cluster}} - {{daemon}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Noobaa CPU / Memory Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Noobaa Pod CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=~\"$cluster\", namespace=\"openshift-storage\", pod=~\"noobaa-.*|.*-noobaa-pod-.*\"}) by (pod)",
       "legendFormat": "{{cluster}} - {{daemon}}"
      }
     ]
    },
    {
     "title": "Noobaa Pod Memory Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=\"openshift-storage\", pod=~\"noobaa-.*|.*-noobaa-pod-.*\", container!=\"\", image!=\"\"}) by (pod)",
       "legendFormat": "{{cluster}} - {{daemon}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Warp POD CPU/Memory Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Warp POD CPU Usage",
     "type": "timeseries",
     "gridPos": { "x": 0, "y": 1, "w": 12, "h": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=~\"$cluster\", namespace=\"default\"}) by (pod)",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Warp POD Memory Usage",
     "type": "timeseries",
     "gridPos": { "x": 12, "y": 1, "w": 12, "h": 8 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=\"default\", container!=\"\", image!=\"\"}) by (pod)",
       "legendFormat": "{{cluster}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node CPU/Memory Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU Usage",
     "type": "timeseries",
     "gridPos": { "x": 0, "y": 10, "w": 12, "h": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - avg by(cluster, instance) (rate(node_cpu_seconds_total{cluster=~\"$cluster\", mode=\"idle\"}[10m]))",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Node Memory Usage",
     "type": "timeseries",
     "gridPos": { "x": 12, "y": 10, "w": 12, "h": 8 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by(cluster, instance) (1 - (node_memory_MemAvailable_bytes{cluster=~\"$cluster\"} / node_memory_MemTotal_bytes{cluster=~\"$cluster\"}))",
       "legendFormat": "{{cluster}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Client Activity : $worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Node RBD Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 129 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(node_disk_read_bytes_total{cluster=~\"$cluster\", instance=~\"$worker\", device=~\"rbd.*\"})"
      }
     ]
    },
    {
     "title": "IOPS : $rbd_device",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 2, "y": 129 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{cluster=~\"$cluster\", device=~\"$rbd_device\", instance=~\"$worker\"}[10m])",
       "legendFormat": "{{cluster}} - Reads"
      },
      {
       "expr": "rate(node_disk_writes_completed_total{cluster=~\"$cluster\", device=~\"$rbd_device\", instance=~\"$worker\"}[10m])",
       "legendFormat": "{{cluster}} - Writes"
      }
     ]
    },
    {
     "title": "Throughput : $rbd_device",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 7, "y": 129 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{cluster=~\"$cluster\", device=~\"$rbd_device\", instance=~\"$worker\"}[10m])",
       "legendFormat": "{{cluster}} - reads"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{cluster=~\"$cluster\", device=~\"$rbd_device\", instance=~\"$worker\"}[10m])",
       "legendFormat": "{{cluster}} - writes"
      }
     ]
    },
    {
     "title": "Latency : $rbd_device",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 12, "y": 129 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_read_time_seconds_total{cluster=~\"$cluster\", instance=\"$worker\", device=~\"$rbd_device\"}[10m]) / clamp_min(rate(node_disk_reads_completed_total{cluster=~\"$cluster\"}[10m]),1))",
       "legendFormat": "{{cluster}} - read"
      },
      {
       "expr": "(rate(node_disk_write_time_seconds_total{cluster=~\"$cluster\", instance=\"$worker\", device=~\"$rbd_device\"}[10m]) / clamp_min(rate(node_disk_writes_completed_total{cluster=~\"$cluster\"}[10m]),1))",
       "legendFormat": "{{cluster}} - write"
      }
     ]
    },
    {
     "title": "Active RBDs (READ)",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 129 },
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{cluster=~\"$cluster\", device=~\"rbd(.*)\", instance=~\"$worker\"}[10m]) > 0"
      }
     ]
    },
    {
     "title": "RBDs Active",
     "type": "stat",
     "description": "Count of rbd images with read activity",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 133 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(rate(node_disk_reads_completed_total{cluster=~\"$cluster\", device=~\"rbd(.*)\", instance=~\"$worker\"}[10m]) > 0)"
      }
     ]
    }
   ]
  },
  {
   "title": "PVC Analysis : $pvc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", persistentvolumeclaim=~\"$pvc\"}"
      }
     ]
    },
    {
     "title": "PVC IOPS : $pvc",
     "type": "timeseries",
     "description": "Needs the rbd_stats_pools set in mgr/prometheus",
     "gridPos": { "h": 12, "w": 7, "x": 2, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "round(rate(ceph_rbd_read_ops{cluster=~\"$cluster\"}[10m]),1)  * on(cluster, image) group_left(volumename) label_replace(ocs_rbd_pv_metadata{cluster=~\"$cluster\"},\"volumename\",\"$1\",\"name\",\"(.*)\") * on(cluster, volumename) group_left(persistentvolumeclaim) kube_persistentvolumeclaim_info{cluster=~\"$cluster\", persistentvolumeclaim=~\"$pvc\"}",
       "legendFormat": "{{cluster}} - {{persistentvolumeclaim}}(R)"
      },
      {
       "expr": "round(rate(ceph_rbd_write_ops{cluster=~\"$cluster\"}[10m]),1) * on(cluster, image) group_left(volumename) label_replace(ocs_rbd_pv_metadata{cluster=~\"$cluster\"},\"volumename\",\"$1\",\"name\",\"(.*)\") * on(cluster, volumename) group_left(persistentvolumeclaim) kube_persistentvolumeclaim_info{cluster=~\"$cluster\", persistentvolumeclaim=~\"$pvc\"}",
       "legendFormat": "{{cluster}} - {{persistentvolumeclaim}}(W)"
      }
     ]
    },
    {
     "title": "PVC Throughput : $pvc",
     "type": "timeseries",
     "description": "Needs the rbd_stats_pools set in mgr/prometheus",
     "gridPos": { "h": 12, "w": 7, "x": 9, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "round(rate(ceph_rbd_read_bytes{cluster=~\"$cluster\"}[10m]),1)  * on(cluster, image) group_left(volumename) label_replace(ocs_rbd_pv_metadata{cluster=~\"$cluster\"},\"volumename\",\"$1\",\"name\",\"(.*)\") * on(cluster, volumename) group_left(persistentvolumeclaim) kube_persistentvolumeclaim_info{cluster=~\"$cluster\", persistentvolumeclaim=~\"$pvc\"}",
       "legendFormat": "{{cluster}} - {{persistentvolumeclaim}}(R)"
      },
      {
       "expr": "round(rate(ceph_rbd_write_bytes{cluster=~\"$cluster\"}[10m]),1) * on(cluster, image) group_left(volumename) label_replace(ocs_rbd_pv_metadata{cluster=~\"$cluster\"},\"volumename\",\"$1\",\"name\",\"(.*)\") * on(cluster, volumename) group_left(persistentvolumeclaim) kube_persistentvolumeclaim_info{cluster=~\"$cluster\", persistentvolumeclaim=~\"$pvc\"}",
       "legendFormat": "{{cluster}} - {{persistentvolumeclaim}}(W)"
      }
     ]
    },
    {
     "title": "PVC Latency : $pvc",
     "type": "timeseries",
     "description": "Needs the rbd_stats_pools set in mgr/prometheus",
     "gridPos": { "h": 12, "w": 7, "x": 16, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "(rate(ceph_rbd_read_latency_sum{cluster=~\"$cluster\"}[10m]) / clamp_min(rate(ceph_rbd_read_latency_count{cluster=~\"$cluster\"}[10m]),1))  * on(cluster, image) group_left(volumename) label_replace(ocs_rbd_pv_metadata{cluster=~\"$cluster\"},\"volumename\",\"$1\",\"name\",\"(.*)\") * on(cluster, volumename) group_left(persistentvolumeclaim) kube_persistentvolumeclaim_info{cluster=~\"$cluster\", persistentvolumeclaim=~\"$pvc\"}",
       "legendFormat": "{{cluster}} - {{persistentvolumeclaim}}(R)"
      },
      {
       "expr": "(rate(ceph_rbd_write_latency_sum{cluster=~\"$cluster\"}[10m]) / clamp_min(rate(ceph_rbd_write_latency_count{cluster=~\"$cluster\"}[10m]),1))  * on(cluster, image) group_left(volumename) label_replace(ocs_rbd_pv_metadata{cluster=~\"$cluster\"},\"volumename\",\"$1\",\"name\",\"(.*)\") * on(cluster, volumename) group_left(persistentvolumeclaim) kube_persistentvolumeclaim_info{cluster=~\"$cluster\", persistentvolumeclaim=~\"$pvc\"}",
       "legendFormat": "{{cluster}} - {{persistentvolumeclaim}}(W)"
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "description": "As  reported by kubelet",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", persistentvolumeclaim=~\"$pvc\"}"
      }
     ]
    },
    {
     "title": "PVC Utilisation",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", persistentvolumeclaim=~\"$pvc\"} / kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", persistentvolumeclaim=~\"$pvc\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Extras",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client IOPS - ALL rbd images",
     "type": "timeseries",
     "description": "Total of IOPS for rbd devices within the cluster",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum(rate(node_disk_reads_completed_total{cluster=~\"$cluster\", device=~\"rbd.*\"}[10m]))",
       "legendFormat": "{{cluster}} - Reads"
      },
      {
       "expr": "sum(rate(node_disk_writes_completed_total{cluster=~\"$cluster\", device=~\"rbd.*\"}[10m]))",
       "legendFormat": "{{cluster}} - Writes"
      }
     ]
    }
   ]
  }
 ]
}